<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="overview" nsURI="http://www.misc.com/tools/moplaf/model/overview/model/0.1"
    nsPrefix="mov">
  <eClassifiers xsi:type="ecore:EClass" name="Overviews">
    <eOperations name="addObject">
      <eParameters name="root" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RootObjects" upperBound="-1"
        eType="#//OverviewObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubOverviews" upperBound="-1"
        eType="#//Overviews" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Remarks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OverviewObject" eSuperTypes="#//OverviewCount">
    <eOperations name="refresh"/>
    <eOperations name="bookInstance">
      <eParameters name="instance" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RootObject" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Remarks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OverviewCount">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Class" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubTypes" upperBound="-1"
        eType="#//OverviewCount" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
