<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tousetimeline" nsURI="http://www.misc.com/touse/moplaf/timeline/model/0.1"
    nsPrefix="ttm">
  <eClassifiers xsi:type="ecore:EClass" name="Domain" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eStructuralFeatures xsi:type="ecore:EReference" name="TimeLineMerges" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.time.discrete.emf/model/timediscrete.ecore#//TimeLineMerge"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Distribution" upperBound="-1"
        eType="#//DomainDistribution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Timelines" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.time.discrete.emf/model/timediscrete.ecore#//TimeLine"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ObjectsWithTimeLine" upperBound="-1"
        eType="#//ConcreteObjectWithTimeLine" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainDistribution" eSuperTypes="../../com.misc.common.moplaf.time.continuous.emf/model/timecontinuous.ecore#//Distribution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Functions" upperBound="-1"
        eType="#//FunctionInterval" containment="true" eOpposite="#//FunctionInterval/Distribution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Possibles" upperBound="-1"
        eType="#//FunctionPossible" containment="true" eOpposite="#//FunctionPossible/Distribution"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionMinimum" eSuperTypes="#//FunctionInterval">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionInterval" abstract="true" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eOperations name="refresh"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Distribution" eType="#//DomainDistribution"
        eOpposite="#//DomainDistribution/Functions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCumulated" eSuperTypes="#//FunctionInterval">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cumulated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0d"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionAverage" eSuperTypes="#//FunctionInterval">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="average" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0d"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionPossible" abstract="true" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eOperations name="refresh"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limitMoment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limitDuration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limitAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Distribution" eType="#//DomainDistribution"
        eOpposite="#//DomainDistribution/Possibles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionEarliestBelow" eSuperTypes="#//FunctionPossible">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="earliestBelow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionEarliestOutput" eSuperTypes="#//FunctionPossible">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="earliestOutput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteObjectWithTimeLine" eSuperTypes="#//SomeBaseClass ../../com.misc.common.moplaf.time.discrete.emf/model/timediscrete.ecore#//ObjectWithTimeLine"/>
  <eClassifiers xsi:type="ecore:EClass" name="SomeBaseClass">
    <eOperations name="someOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="someAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteObjectTimeBucket" eSuperTypes="#//SomeBaseClass ../../com.misc.common.moplaf.time.discrete.emf/model/timediscrete.ecore#//ObjectTimeBucket">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="ConcreteObjectWithTimeLine"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
