<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tousesolverlp" nsURI="http://www.misc.com/common/touse/solverlp/model/0.1"
    nsPrefix="tsollp">
  <eClassifiers xsi:type="ecore:EClass" name="Folder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubFolders" upperBound="-1"
        eType="#//Folder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Generators" upperBound="-1"
        eType="#//ToUseGenerator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseGenerator" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//Generator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RootTuples" upperBound="-1"
        eType="#//ToUseTuple" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solvers" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//Solver"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseTuple" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ChildTuples" upperBound="-1"
        eType="#//ToUseTuple" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ToUseVars" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ToUseCons" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
