<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tousescheduler" nsURI="http://www.misc.com/touse/moplaf/scheduler/model/0.1"
    nsPrefix="tus">
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Schedulers" upperBound="-1"
        eType="#//ToUseScheduler" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Vehicles" upperBound="-1"
        eType="#//Vehicle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Shipments" upperBound="-1"
        eType="#//Shipment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Shipment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseScheduler" eSuperTypes="../../com.misc.common.moplaf.scheduler.emf/model/scheduler.ecore#//Scheduler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SelectedVehicles" upperBound="-1"
        eType="#//Vehicle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SelectedShipments" upperBound="-1"
        eType="#//Shipment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseSchedule" eSuperTypes="../../com.misc.common.moplaf.scheduler.emf/model/scheduler.ecore#//Schedule">
    <eOperations name="enable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Actions" upperBound="-1"
        eType="#//ToUseAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseScore" eSuperTypes="../../com.misc.common.moplaf.localsearch.emf/model/localsearch.ecore#//Score">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TotalDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseScheduleResource" eSuperTypes="../../com.misc.common.moplaf.scheduler.emf/model/scheduler.ecore#//Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Vehicle" lowerBound="1"
        eType="#//Vehicle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TotalDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseScheduleTask" eSuperTypes="../../com.misc.common.moplaf.scheduler.emf/model/scheduler.ecore#//Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Shipment" lowerBound="1"
        eType="#//Shipment" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseLoadShipment" eSuperTypes="#//ToUseScheduleTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ShipmentLoaded" eType="#//Shipment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="UnloadShipment" lowerBound="1"
        eType="#//ToUseUnloadShipment" eOpposite="#//ToUseUnloadShipment/LoadShipment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseUnloadShipment" eSuperTypes="#//ToUseScheduleTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ShipmentUnloaded" eType="#//Shipment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LoadShipment" lowerBound="1"
        eType="#//ToUseLoadShipment" eOpposite="#//ToUseLoadShipment/UnloadShipment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseScheduleLoadUnload" eSuperTypes="#//ToUseAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="LoadTask" lowerBound="1"
        eType="#//ToUseLoadShipment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalcScheduler" abstract="true" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//PropagatorFunctionBindings"/>
  <eClassifiers xsi:type="ecore:EClass" name="CalcSchedule" abstract="true" eSuperTypes="#//CalcScheduler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Schedule" lowerBound="1"
        eType="#//ToUseSchedule" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalcResource" abstract="true" eSuperTypes="#//CalcScheduler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" lowerBound="1"
        eType="#//ToUseScheduleResource" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalcTask" abstract="true" eSuperTypes="#//CalcScheduler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Task" lowerBound="1" eType="#//ToUseScheduleTask"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScopeScheduleScore" eSuperTypes="#//CalcSchedule"/>
  <eClassifiers xsi:type="ecore:EClass" name="LayerScheduleDistance" eSuperTypes="#//CalcSchedule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" lowerBound="1"
        eType="#//ScopeScheduleScore" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalcTaskDistance" eSuperTypes="#//CalcTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" lowerBound="1"
        eType="#//LayerScheduleDistance" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CalcResourceDistance" eSuperTypes="#//CalcResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConcreteParent" lowerBound="1"
        eType="#//LayerScheduleDistance" changeable="false" volatile="true" transient="true"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseAction" eSuperTypes="../../com.misc.common.moplaf.localsearch.emf/model/localsearch.ecore#//Action"/>
</ecore:EPackage>
