<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gistouse" nsURI="http://www.misc.com/touse.moplaf.solver.emf"
    nsPrefix="tgis">
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Locations" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.gis.emf/model/gis.ecore#//GisLocation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Matrices" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.gis.emf/model/gis.ecore#//GisRoutesHolder"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
