<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tousepropagator2" nsURI="http://www.misc.com/touse/moplaf/propagator2/model/0.1"
    nsPrefix="top">
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Projects" upperBound="-1"
        eType="#//Project" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Thing"/>
    </eAnnotations>
    <eOperations name="refreshEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tasks" upperBound="-1"
        eType="#//Task" containment="true" eOpposite="#//Task/Project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Dependences" upperBound="-1"
        eType="#//Dependence" containment="true" eOpposite="#//Dependence/Project"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NofRes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        transient="true" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="2001-01-01"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="End" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="2001-01-01">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ProjectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" upperBound="-1"
        eType="#//Resource" containment="true" eOpposite="#//Resource/Project"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AutomaticRefresh" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eOperations name="refreshStart"/>
    <eOperations name="refreshEnd"/>
    <eOperations name="refreshHours"/>
    <eOperations name="refreshHoursItem"/>
    <eOperations name="refreshHoursVar"/>
    <eOperations name="refreshResourceCandidates">
      <eParameters name="resource" eType="#//Resource"/>
    </eOperations>
    <eOperations name="refreshResourceCandidates"/>
    <eOperations name="dispose"/>
    <eOperations name="isCandidate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="resource" eType="#//Resource"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="2001-01-01">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="End" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="2001-01-01">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HoursItems" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HoursVar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HoursVarPerRes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DependencesAfter" upperBound="-1"
        eType="#//Dependence" eOpposite="#//Dependence/TaskBefore"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DependencesBefore" upperBound="-1"
        eType="#//Dependence" eOpposite="#//Dependence/TaskAfter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TaskName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="new task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Items" upperBound="-1"
        eType="#//TaskItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/Tasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResourceCandidates" upperBound="-1"
        eType="#//ResourceCandidate" containment="true" eOpposite="#//ResourceCandidate/Task"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskWithOverhead" eSuperTypes="#//Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HoursOverhead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependence" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//ObjectWithPropagatorFunctions">
    <eOperations name="dispose"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TaskBefore" lowerBound="1"
        eType="#//Task" eOpposite="#//Task/DependencesAfter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TaskAfter" lowerBound="1"
        eType="#//Task" eOpposite="#//Task/DependencesBefore"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/Dependences"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Notes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="new item"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="2001-01-01">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="End" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="2001-01-01">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/Resources"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ResourceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceCandidate">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resource" eType="#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Match" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Task" lowerBound="1" eType="#//Task"
        eOpposite="#//Task/ResourceCandidates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUsePropagatorFunction" eSuperTypes="../../com.misc.common.moplaf.propagator2/model/propagator.ecore#//PropagatorFunctionBindings">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Calculated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUsePropagatorFunctionTask" eSuperTypes="#//ToUsePropagatorFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Task" lowerBound="1" eType="#//Task"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUsePropagatorFunctionProject" eSuperTypes="#//ToUsePropagatorFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Project" lowerBound="1"
        eType="#//Project" changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
</ecore:EPackage>
