<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tousejob" nsURI="//www.misc.com/touse/moplaf/job/model/0.1"
    nsPrefix="tuj">
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Runs" upperBound="-1" eType="#//Runs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Proxies" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.job.client.emf/model/jobclient.ecore#//JobEngineProxy"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobscheduler" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.job.client.emf/model/jobclient.ecore#//JobScheduler"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseJob" eSuperTypes="../../com.misc.common.moplaf.job.emf/model/job.ecore#//Job">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SecondsWaiting" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="2"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Iteration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseJobResult" eSuperTypes="../../com.misc.common.moplaf.job.client.emf/model/jobclient.ecore#//JobRemoteResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TicksWaited" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DummyToHoldRefToModel" abstract="true"
      interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseJobConsole" eSuperTypes="../../com.misc.common.moplaf.job.emf/model/job.ecore#//JobConsole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CallerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Runs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Runs" upperBound="-1" eType="ecore:EClass ../../com.misc.common.moplaf.job.emf/model/job.ecore#//Run"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
