<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MetaModelBlog">
  <eClassifiers xsi:type="ecore:EClass" name="VehicleTravelLeg" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Planned" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DrivenKm" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NotOverloaded" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FromLocation" lowerBound="1"
        eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ToLocation" lowerBound="1"
        eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Vehicle" lowerBound="1"
        eType="#//Vehicle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location"/>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle"/>
</ecore:EPackage>
