<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tousesolver" nsURI="http://www.misc.com/touse/moplaf/solver/model/0.1"
    nsPrefix="tos">
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RootFolder" upperBound="-1"
        eType="#//DomainObjectFolder" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Knapsack" eSuperTypes="#//DomainObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="#//DomainObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShortName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainObjectFolder">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Object" upperBound="-1"
        eType="#//DomainObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubFolder" upperBound="-1"
        eType="#//DomainObjectFolder" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scenario" upperBound="-1"
        eType="#//Scenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Knapsack" lowerBound="1"
        eType="#//Knapsack"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Item" lowerBound="1" upperBound="-1"
        eType="#//Item"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LP" upperBound="-1" eType="#//KnapsackLp"
        containment="true" eOpposite="#//KnapsackLp/Scenario"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Sol" upperBound="-1" eType="#//KnapsackSol"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Remarks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SolutionReader" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//SolutionReader"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnapsackSol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TotalValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TotalWeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solver" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//Solution"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Item" upperBound="-1" eType="#//Item"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Lp" eType="#//KnapsackLp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KnapsackLp" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//Generator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Root" lowerBound="1" eType="#//LpRoot"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scenario" lowerBound="1"
        eType="#//Scenario" eOpposite="#//Scenario/LP"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Value" lowerBound="1" eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpGoal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solver" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//Solver"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpRoot" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Item" upperBound="-1" eType="#//LpItem"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Knapsack" lowerBound="1"
        eType="#//LpKnapsack" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpKnapsack" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Knapsack" lowerBound="1"
        eType="#//Knapsack"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConsCapacity" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpCons"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LpItem" eSuperTypes="../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorTuple">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Item" lowerBound="1" eType="#//Item"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VarInKnapsack" lowerBound="1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//GeneratorLpVar"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
