<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="macroplanner" nsURI="http://www.misc.com/touse/moplaf/macroplanner/model/0.1"
    nsPrefix="mptu">
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="MasterData" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//SupplyChainMasterData"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Limits" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//SupplyChainLimits"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Routings" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//SupplyChainRoutings"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Data" upperBound="-1" eType="ecore:EClass ../../com.misc.common.moplaf.macroplanner.emf/model/MacroPlanner.ecore#//SupplyChainData"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Scenarios" upperBound="-1"
        eType="#//ToUseScenario" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseLPMacroPlanner" eSuperTypes="../../com.misc.common.moplaf.macroplanner.solver.emf/model/MacroPlannerSolver.ecore#//LPMacroPlanner">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Solvers" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.solver.emf/model/solver.ecore#//Solver"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseScenario" eSuperTypes="../../com.misc.common.moplaf.macroplanner.solver.emf/model/MacroPlannerSolver.ecore#//Scenario"/>
</ecore:EPackage>
