<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tousespreadsheet" nsURI="http://www.misc.com/touse/moplaf/spreadsheet/model/0.1"
    nsPrefix="tusp">
  <eClassifiers xsi:type="ecore:EClass" name="Domain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SpreadsheetsPOI" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.spreadsheet.poi.emf/model/spreadsheetpoi.ecore#//SpreadsheetPOI"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SpreadsheetsCSV" upperBound="-1"
        eType="ecore:EClass ../../com.misc.common.moplaf.spreadsheet.csv.emf/model/spreadsheetcsv.ecore#//SpreadsheetCSV"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Tables" upperBound="-1"
        eType="#//ToUseTable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Items" upperBound="-1"
        eType="#//ToUseTableItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToUseTableItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LongAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LongAttributeColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ItemName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
